### ISSUE TITLE
live mode

### ISSUE THREAD

**Issue by yizhoucao** [yizhoucao/lilith#12]
-right now all calculation are effectively for eod or historical mode.
-need to differentiate between live and eod mode. 
-for live mode, we can subscribe price updates from firebase
-live prices can be stored in a seperate table just for live prices.

**Comment by jeerrry** [comment]
A few thoughts:
* In live mode users' attention should be on current price and MV, rather than past performance. There's no need to put the chart at top.
* Therefore we shall build another layout for live mode.
* We wouldn't want to direct user to another webpage which means reloading data or using cookies, that's the old way. We would rather let them use the current page like an app, i.e. web app. For this we might need to use modern front-end frameworks like react, angular2 or vue.js.
* At current stage we can try building a separate table for the live mode at index page. Just to test out the feature.

**Comment by yizhoucao** [comment]
data subscription is done, but one issue with display. right now table and chart are drawn in the same function call. whenever there is a price update, both will be updated while chart data is not changed.

need to separate chart and table drawing and live price update should on redraw the table.
